name: test_shceduler
on:
  workflow_dispatch:

jobs:
  download:
    strategy:
      matrix:
        param: [v1, v2, v3, v4, v5, v6, v7, v8]
    runs-on: linux-aarch64-a3-4
    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:8.2.rc1.alpha003-910b-openeuler22.03-py3.11

    steps:
      - name: Sleep
        run: |
          npu-smi info