name: sync datasets and models to our persistent storage
on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch:

jobs:
  sync_dataset:
    runs-on: linux-arm64-npu-1
    container:
      image: m.daocloud.io/docker.io/python:3.11
    steps:
      - name: check env
        run: |
          cat ~/.gitconfig
          curl https://gh-proxy.test.osinfra.cn
      - uses: actions/checkout@v4
      - name: download models
        run: |
          cat ~/.gitconfig
          curl https://gh-proxy.test.osinfra.cn
          pip install modelscope
          for m in `cat .github/workflows/model_list.ini`;do modelscope download  --model $m;done 
      - name: download dataset
        run: |
          for m in `cat .github/workflows/dataset_list.ini`;do modelscope download  --dataset $m;done 

