name: test npu
on:
  workflow_dispatch:

jobs:
  test1:
    runs-on: linux-arm64-npu-1
    container:
      image: m.daocloud.io/quay.io/ascend/cann:8.1.rc1-910b-ubuntu22.04-py3.10
    steps:
      - name: Sleep
        run: |
          npu-smi info
  test2:
    runs-on: linux-arm64-npu-2
    container:
      image: m.daocloud.io/quay.io/ascend/cann:8.1.rc1-910b-ubuntu22.04-py3.10
    steps:
      - name: Sleep
        run: |
          npu-smi info
  test4:
    runs-on: linux-arm64-npu-4
    container:
      image: m.daocloud.io/quay.io/ascend/cann:8.1.rc1-910b-ubuntu22.04-py3.10
    steps:
      - name: Sleep
        run: |
          npu-smi info
