name: test npu
on:
  workflow_dispatch:

jobs:
  test1:
    runs-on: linux-arm64-npu-1
    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:8.2.rc1.alpha003-910b-openeuler22.03-py3.11
    steps:
      - name: Sleep
        run: |
          npu-smi info
  test2:
    runs-on: linux-arm64-npu-2
    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:8.2.rc1.alpha003-910b-openeuler22.03-py3.11
    steps:
      - name: Sleep
        run: |
          npu-smi info
  test4:
    runs-on: linux-arm64-npu-4
    container:
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/ascend-ci/cann:8.2.rc1.alpha003-910b-openeuler22.03-py3.11
    steps:
      - name: Sleep
        run: |
          npu-smi info
